---
name: main

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!source'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Node.js dependencies
        run: npm install
      - name: Build
        run: bundle exec rake build
