---
name: release

on:
  push:
    tags:
      - v*

jobs:
  github:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec rake
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: eve-overview-*.zip
